server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${DB_URL}
      auto-index-creation: true  # 인덱스 자동 생성 설정 추가
    redis:
      host: localhost
      port: 6379
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
  #    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  #    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  mail:
    host: smtp.gmail.com  # Gmail의 SMTP 서버 호스트
    port: 587 # Gmail SMTP 서버는 587번 포트를 사용
    username: ${MAIL_APP_USERNAME}
    password: ${MAIL_APP_PW}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          connectiontimeout: 5000 # 연결 타임아웃 (ms)
          starttls.enable: true # TLS 활성화 여부

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
#        data:
#          mongodb: DEBUG
#      mongodb: DEBUG

jwt:
  expiration: 86400000 #1일
  secret: ${JWT_SECRET}